version: 2
updates:
- package-ecosystem: nuget
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: System.IO.Abstractions
    versions:
    - 13.2.10
    - 13.2.11
    - 13.2.15
    - 13.2.17
    - 13.2.20
    - 13.2.23
    - 13.2.24
    - 13.2.25
    - 13.2.28
    - 13.2.9
  - dependency-name: Moq
    versions:
    - 4.16.0
  - dependency-name: Autofac
    versions:
    - 6.1.0
  - dependency-name: SecurityCodeScan
    versions:
    - 3.5.3
